// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts — used by Prisma CLI only (not compiled by tsc)
import "dotenv/config";
// @ts-expect-error Prisma CLI resolves this config helper at runtime.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "mysql://root@localhost:3307/dostoori",
  },
});
